/**
 * Mapping from artifact set ID to the 5 individual piece names.
 * Order: [Flower, Plume/Feather, Sands, Goblet, Circlet]
 *
 * These are the official in-game names for each artifact piece,
 * sourced from the Genshin Impact Wiki.
 */
export const ARTIFACT_PIECE_NAMES: Record<string, [string, string, string, string, string]> = {
  thundering_fury: [
    "Thunderbird's Mercy",
    "Survivor of Catastrophe",
    "Hourglass of Thunder",
    "Omen of Thunderstorm",
    "Thunder Summoner's Crown",
  ],
  thundersoother: [
    "Thundersoother's Heart",
    "Thundersoother's Plume",
    "Hour of Soothing Thunder",
    "Thundersoother's Goblet",
    "Thundersoother's Diadem",
  ],
  archaic_petra: [
    "Flower of Creviced Cliff",
    "Feather of Jagged Peaks",
    "Sundial of Enduring Jade",
    "Goblet of Chiseled Crag",
    "Mask of Solitude Basalt",
  ],
  retracing_bolide: [
    "Summer Night's Bloom",
    "Summer Night's Finale",
    "Summer Night's Moment",
    "Summer Night's Waterballoon",
    "Summer Night's Mask",
  ],
  viridescent_venerer: [
    "In Remembrance of Viridescent Fields",
    "Viridescent Arrow Feather",
    "Viridescent Venerer's Determination",
    "Viridescent Venerer's Vessel",
    "Viridescent Venerer's Diadem",
  ],
  maiden_beloved: [
    "Maiden's Distant Love",
    "Maiden's Heart-Stricken Infatuation",
    "Maiden's Passing Youth",
    "Maiden's Fleeting Leisure",
    "Maiden's Fading Beauty",
  ],
  crimson_witch_of_flames: [
    "Witch's Flower of Blaze",
    "Witch's Ever-Burning Plume",
    "Witch's End Time",
    "Witch's Heart Flames",
    "Witch's Scorching Hat",
  ],
  lavawalker: [
    "Lavawalker's Resolution",
    "Lavawalker's Salvation",
    "Lavawalker's Torment",
    "Lavawalker's Epiphany",
    "Lavawalker's Wisdom",
  ],
  bloodstained_chivalry: [
    "Bloodstained Flower of Iron",
    "Bloodstained Black Plume",
    "Bloodstained Final Hour",
    "Bloodstained Chevalier's Goblet",
    "Bloodstained Iron Mask",
  ],
  noblesse_oblige: [
    "Royal Flora",
    "Royal Plume",
    "Royal Pocket Watch",
    "Royal Silver Urn",
    "Royal Masque",
  ],
  blizzard_strayer: [
    "Snowswept Memory",
    "Icebreaker's Resolve",
    "Frozen Homeland's Demise",
    "Frost-Weaved Dignity",
    "Broken Rime's Echo",
  ],
  heart_of_depth: [
    "Gilded Corsage",
    "Gust of Nostalgia",
    "Copper Compass",
    "Goblet of Thundering Deep",
    "Wine-Stained Tricorne",
  ],
  tenacity_of_the_millelith: [
    "Flower of Accolades",
    "Ceremonial War-Plume",
    "Orichalceous Time-Dial",
    "Noble's Pledging Vessel",
    "General's Ancient Helm",
  ],
  pale_flame: [
    "Stainless Bloom",
    "Wise Doctor's Pinion",
    "Moment of Cessation",
    "Surpassing Cup",
    "Mocking Mask",
  ],
  shimenawas_reminiscence: [
    "Entangling Bloom",
    "Shaft of Remembrance",
    "Morning Dew's Moment",
    "Hopeful Heart",
    "Capricious Visage",
  ],
  emblem_of_severed_fate: [
    "Magnificent Tsuba",
    "Sundered Feather",
    "Storm Cage",
    "Scarlet Vessel",
    "Ornate Kabuto",
  ],
  husk_of_opulent_dreams: [
    "Bloom Times",
    "Plume of Luxury",
    "Song of Life",
    "Calabash of Awakening",
    "Skeletal Hat",
  ],
  ocean_hued_clam: [
    "Sea-Dyed Blossom",
    "Deep Palace's Plume",
    "Cowry of Parting",
    "Pearl Cage",
    "Crown of Watatsumi",
  ],
  vermillion_hereafter: [
    "Flowering Life",
    "Feather of Nascent Light",
    "Solar Relic",
    "Moment of the Pact",
    "Thundering Poise",
  ],
  echoes_of_an_offering: [
    "Soulscent Bloom",
    "Jade Leaf",
    "Symbol of Felicitation",
    "Chalice of the Font",
    "Flowing Rings",
  ],
  deepwood_memories: [
    "Labyrinth Wayfarer",
    "Scholar of Vines",
    "A Time of Insight",
    "Lamp of the Lost",
    "Laurel Coronet",
  ],
  gilded_dreams: [
    "Dreaming Steelbloom",
    "Feather of Judgment",
    "The Sunken Years",
    "Honeyed Final Feast",
    "Shadow of the Sand King",
  ],
  desert_pavilion_chronicle: [
    "The First Days of the City of Kings",
    "End of the Golden Realm",
    "Timepiece of the Lost Path",
    "Defender of the Enchanting Dream",
    "Legacy of the Desert High-Born",
  ],
  flower_of_paradise_lost: [
    "Ay-Khanoum's Myriad",
    "Wilting Feast",
    "A Moment Congealed",
    "Secret-Keeper's Magic Bottle",
    "Amethyst Crown",
  ],
  nymphs_dream: [
    "Odyssean Flower",
    "Wicked Mage's Plumule",
    "Nymph's Constancy",
    "Heroes' Tea Party",
    "Fell Dragon's Monocle",
  ],
  vourukashas_glow: [
    "Stamen of Khvarena's Origin",
    "Vibrant Pinion",
    "Ancient Abscission",
    "Feast of Boundless Joy",
    "Heart of Khvarena's Brilliance",
  ],
  marechaussee_hunter: [
    "Hunter's Brooch",
    "Masterpiece's Overture",
    "Moment of Judgment",
    "Forgotten Vessel",
    "Veteran's Visage",
  ],
  golden_troupe: [
    "Golden Song's Variation",
    "Golden Bird's Shedding",
    "Golden Era's Prelude",
    "Golden Night's Bustle",
    "Golden Troupe's Reward",
  ],
  nighttime_whispers: [
    "Selfless Floral Accessory",
    "Honest Quill",
    "Faithful Hourglass",
    "Magnanimous Ink Bottle",
    "Compassionate Ladies' Hat",
  ],
  song_of_days_past: [
    "Forgotten Oath of Days Past",
    "Recollection of Days Past",
    "Echoing Sound From Days Past",
    "Promised Dream of Days Past",
    "Poetry of Days Past",
  ],
  fragment_of_harmonic_whimsy: [
    "Harmonious Symphony Prelude",
    "Ancient Sea's Nocturnal Musing",
    "The Grand Jape of the Turning of Fate",
    "Ichor Shower Rhapsody",
    "Whimsical Dance of the Withered",
  ],
  unfinished_reverie: [
    "Dark Fruit of Bright Flowers",
    "Faded Emerald Tail",
    "Moment of Attainment",
    "The Wine-Flask Over Which the Plan Was Hatched",
    "Crownless Crown",
  ],
  scroll_of_the_hero_of_cinder_city: [
    "Beast Tamer's Talisman",
    "Mountain Ranger's Marker",
    "Mystic's Gold Dial",
    "Wandering Scholar's Claw Cup",
    "Demon-Warrior's Feather Mask",
  ],
  obsidian_codex: [
    "Reckoning of the Xenogenic",
    "Root of the Spirit-Marrow",
    "Myths of the Night Realm",
    "Pre-Banquet of the Contenders",
    "Crown of the Saints",
  ],
  finale_of_the_deep_galleries: [
    "Deep Gallery's Echoing Song",
    "Deep Gallery's Distant Pact",
    "Deep Gallery's Moment of Oblivion",
    "Deep Gallery's Bestowed Banquet",
    "Deep Gallery's Lost Crown",
  ],
  long_nights_oath: [
    "Lightkeeper's Pledge",
    "Nightingale's Tail Feather",
    "Undying One's Mourning Bell",
    "A Horn Unwinded",
    "Dyed Tassel",
  ],
  night_of_the_skys_unveiling: [
    "Bloom of the Mind's Desire",
    "Feather of Indelible Sin",
    "Revelation's Toll",
    "Vessel of Plenty",
    "Crown of the Befallen",
  ],
  silken_moons_serenade: [
    "Crystal Tear of the Wanderer",
    "Pristine Plume of the Blessed",
    "Frost Devotee's Delirium",
    "Joyous Glory of the Pure",
    "Holy Crown of the Believer",
  ],
  a_day_carved_from_rising_winds: [
    "Windborne Flower's Spruchdichtung",
    "Dawn's Brilliant Oath",
    "A Note in Spring's Leich",
    "Heldenepos's Unspoken Tale",
    "Minnesang of Love and Lament",
  ],
  aubade_of_morningstar_and_moon: [
    "Moonlit Offering's Opulent Dream",
    "Moonlit Offering's Parting Light",
    "Moonlit Offering's Final Hour",
    "Moonlit Offering's Libation",
    "Moonlit Offering's Silver Crown",
  ],
  celestial_gift: [
    "Heavensent Fragrance",
    "Heavensent Demise",
    "Heavensent Decree",
    "Heavensent Reward",
    "Heavensent Crown",
  ],
  disenchantment_in_deep_shadow: [
    "Iridescence That Ceased Amidst Glory",
    "Sharpness That Ceased Upon Wondrous Creation",
    "Moment That Ceased Upon Waking From Grand Dreams",
    "Ovations That Ceased Upon Festivity",
    "Pendulum That Ceased Amidst a Great Fall",
  ],
  heart_of_the_furnace: [
    "Foundryman's Conjecture",
    "Foundryman's Observation",
    "Foundryman's Calculus",
    "Foundryman's Magnanimity",
    "Foundryman's Legacy",
  ],
  scarlet_proof: [
    "Honor to Your Devotion",
    "Glory to Your Legacy",
    "Time Gifted Unto You",
    "Chalice of Your Blood and Sorrow",
    "Testament to Your Faith",
  ],
}

/**
 * Generic slot type names used as subtitle (e.g. "Plume of Death" style).
 * These are the generic Genshin artifact slot categories.
 */
export const SLOT_TYPE_NAMES = [
  "Flower of Life",
  "Plume of Death",
  "Sands of Eon",
  "Goblet of Eonothem",
  "Circlet of Logos",
]
