import { Stat, Slot } from "../constants/artifactData"
import type { ArtifactOutput } from "../types/artifact"
import type { IArtifact, IGOOD, SlotKey, StatKey } from "../types/good"

export const INTERNAL_TO_GOOD_STAT: Record<number, StatKey> = {
  [Stat.CritDMG]: "critDMG_",
  [Stat.CritRate]: "critRate_",
  [Stat.ElementalMastery]: "eleMas",
  [Stat.EnergyRecharge]: "enerRech_",
  [Stat.AtkPercent]: "atk_",
  [Stat.FlatAtk]: "atk",
  [Stat.HpPercent]: "hp_",
  [Stat.FlatHp]: "hp",
  [Stat.DefPercent]: "def_",
  [Stat.FlatDef]: "def",
  [Stat.HealingBonus]: "heal_",
  [Stat.PyroDMG]: "pyro_dmg_",
  [Stat.HydroDMG]: "hydro_dmg_",
  [Stat.ElectroDMG]: "electro_dmg_",
  [Stat.CryoDMG]: "cryo_dmg_",
  [Stat.AnemoDMG]: "anemo_dmg_",
  [Stat.GeoDMG]: "geo_dmg_",
  [Stat.DendroDMG]: "dendro_dmg_",
  [Stat.PhysicalDMG]: "physical_dmg_",
}

export const INTERNAL_TO_GOOD_SLOT: Record<number, SlotKey> = {
  [Slot.Flower]: "flower",
  [Slot.Feather]: "plume",
  [Slot.Sands]: "sands",
  [Slot.Goblet]: "goblet",
  [Slot.Circlet]: "circlet",
}

export function exportArtifactToGOOD(
  artifact: ArtifactOutput,
  setKey: string = "GladiatorsFinale", // Provide a default or pass it in since we don't have sets internally yet
  location: string = "",
  lock: boolean = false
): IArtifact {
  return {
    setKey,
    slotKey: INTERNAL_TO_GOOD_SLOT[artifact.slot] ?? "flower",
    level: artifact.level,
    rarity: 5, // Assuming 5-star artifacts generated by engine
    mainStatKey: INTERNAL_TO_GOOD_STAT[artifact.mainStat.type] ?? "hp",
    location,
    lock,
    substats: artifact.subStats.map((sub) => ({
      key: INTERNAL_TO_GOOD_STAT[sub.type] ?? "hp",
      value: sub.value,
      // You can add logic to infer initialValue from rolls if needed for GOOD 3
    })),
    // Optional GOOD 3 fields could be added here
  }
}

export function exportSimulationToGOOD(artifacts: ArtifactOutput[]): IGOOD {
  return {
    format: "GOOD",
    version: 3,
    source: "ArtifactSpeculationEngine",
    artifacts: artifacts.map(art => exportArtifactToGOOD(art)),
  }
}
